"""Protocol for the deterministic core persistence boundary."""

from __future__ import annotations

from typing import Protocol

from quorum.domain.models import Assignment, Gap, LedgerEntry, PendingEffect, Shift, Volunteer


class Store(Protocol):
    def get_shift(self, shift_id: str) -> Shift | None: ...
    def list_volunteers(self) -> list[Volunteer]: ...
    def list_assignments(self, shift_id: str) -> list[Assignment]: ...
    def upsert_gap(self, gap: Gap) -> Gap: ...
    def append_ledger(self, entry: LedgerEntry) -> None: ...
    def create_pending(self, pending: PendingEffect) -> PendingEffect: ...
